---
title: "Gutenberg Scraper"
author: "(Eliza) Zijin Huang"
date: "4/8/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rvest)
library(stringr)
```

## Birth Year Scraper
Extracting top 100 authors names, and link to the details (birth year, publications)
```{r bday}
page <- 'https://www.gutenberg.org/browse/scores/top#authors-last1' %>% read_html()
html <- html_nodes(page, '#authors-last1+ ol a')

names <- html_text(html) %>% 
  sapply(function(name) return(gsub(' \\([[:digit:]]+\\)', '', name)))

urls <- html %>%
  html_attr("href") %>% 
  sapply(function(url) return(paste("https://www.gutenberg.org", url, sep=""))) 

data <- cbind(names, urls)
```

Extract birth year from link
```{r bday}
remove_na <- function(vector) {
  return (vector[!is.na(vector)])
}

get_info <- function(name, url) {
  author <- read_html(url)
  author_html <- html_nodes(author, 'h2 a:nth-child(1)')
  info <- html_text(author_html) %>%
    str_extract(paste0(name, "1.+")) %>%
    remove_na()
  return(info)
}

# birth <- mapply(get_info, data[, "names"], data[, "urls"])
```

Export the names, urls, birth years to data.csv 

```{r}
birth
birth_year <- birth %>% 
  lapply(function(info) str_extract(info, "[:digit:]+\\-")) %>% 
  lapply(function(info) str_replace(info, "-", "")) 
birth_year
write.csv(birth_year, file = "data.csv")
```
